# -*- coding: utf-8 -*-
"""PROGCOM-A (codigo del video)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pa8udw12Wcnd-sxGZv5fr931qTfLlZ62
"""

def manaso(lado):
  print(f"Manaso vertical a la {lado}")

manaso("derecha")
manaso("izquierda")

def remolino(lado):
  print(f"remolino horizontal {lado}")

remolino ("derecha")
remolino ("izquierda")

def manaso1(repeticiones):
    for _ in range(repeticiones):
        print(f"Manaso vertical a la derecha")
        print(f"Manaso vertical a la izquierda")

def remolino1(lado, repeticiones):
    for _ in range(repeticiones):
        print(f"remolino horizontal {lado}")


manaso1(4)
manaso("izquierda", 4)